package screens;

import models.Arma;
import models.Inimigo;
import models.Personagem;
import tools.Globais;

/**
 *
 * @author maaschmidt
 */
public class TelaMissao extends javax.swing.JFrame {
    
    Inimigo[] objInimigo = new Inimigo[11];
    private int missao = 1;
    Personagem personagemEscolhido = new Personagem();
    Arma armaEscolhida = new Arma();
    Inimigo inimigo = new Inimigo();
    
    /**
     * Creates new form TelaMissão
     * @param personagemEscolhido
     * @param armaEscolhida
     */
    public TelaMissao(Personagem personagemEscolhido, Arma armaEscolhida) {
        initComponents();
        setInimigos();
        this.personagemEscolhido = personagemEscolhido;
        this.armaEscolhida = armaEscolhida;
        setTela();
        pontosMissoes(1);
    }

    TelaMissao(int idInimigo, Personagem personagemEscolhido, Arma armaEscolhida) {
        initComponents();
        setInimigos();
        this.missao = idInimigo;
        this.personagemEscolhido = personagemEscolhido;
        this.armaEscolhida = armaEscolhida;
        setTela();
        pontosMissoes(idInimigo);
    }

    private TelaMissao() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlDados = new javax.swing.JPanel();
        lblMoney = new javax.swing.JLabel();
        lblMoneyIco = new javax.swing.JLabel();
        lblRS = new javax.swing.JLabel();
        pgbMunicao = new javax.swing.JProgressBar();
        pgbVida = new javax.swing.JProgressBar();
        btnStore = new javax.swing.JButton();
        btnSairDados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMunicao = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        pnlMonitor = new javax.swing.JPanel();
        btnAceitar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblMissao = new javax.swing.JLabel();
        lblInimigo = new javax.swing.JLabel();
        lblMonitor = new javax.swing.JLabel();
        lblFundo1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnDados = new javax.swing.JButton();
        btnCidade1 = new javax.swing.JButton();
        btnCidade2 = new javax.swing.JButton();
        btnCidade3 = new javax.swing.JButton();
        btnInterior4 = new javax.swing.JButton();
        btnCidade5 = new javax.swing.JButton();
        btnInterior6 = new javax.swing.JButton();
        btnInterior7 = new javax.swing.JButton();
        btnCidade8 = new javax.swing.JButton();
        btnInterior9 = new javax.swing.JButton();
        btnInterior10 = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDados.setBackground(new java.awt.Color(51, 51, 51));
        pnlDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDados.setLayout(null);

        lblMoney.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblMoney.setForeground(new java.awt.Color(255, 255, 255));
        lblMoney.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlDados.add(lblMoney);
        lblMoney.setBounds(110, 20, 90, 20);
        pnlDados.add(lblMoneyIco);
        lblMoneyIco.setBounds(40, 10, 40, 40);

        lblRS.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblRS.setForeground(new java.awt.Color(255, 255, 255));
        lblRS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRS.setText("R$");
        pnlDados.add(lblRS);
        lblRS.setBounds(80, 20, 30, 20);

        pgbMunicao.setFont(new java.awt.Font("Checkpoint Charlie", 0, 13)); // NOI18N
        pgbMunicao.setValue(75);
        pgbMunicao.setBorderPainted(false);
        pgbMunicao.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pgbMunicao.setString("MUNICAO");
        pgbMunicao.setStringPainted(true);
        pnlDados.add(pgbMunicao);
        pgbMunicao.setBounds(30, 60, 146, 16);

        pgbVida.setFont(new java.awt.Font("Checkpoint Charlie", 0, 13)); // NOI18N
        pgbVida.setValue(75);
        pgbVida.setBorderPainted(false);
        pgbVida.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pgbVida.setString("VIDA");
        pgbVida.setStringPainted(true);
        pnlDados.add(pgbVida);
        pgbVida.setBounds(30, 120, 146, 16);

        btnStore.setBorderPainted(false);
        btnStore.setContentAreaFilled(false);
        btnStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreActionPerformed(evt);
            }
        });
        pnlDados.add(btnStore);
        btnStore.setBounds(90, 190, 40, 40);

        btnSairDados.setBorderPainted(false);
        btnSairDados.setContentAreaFilled(false);
        btnSairDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairDadosActionPerformed(evt);
            }
        });
        pnlDados.add(btnSairDados);
        btnSairDados.setBounds(180, 230, 20, 20);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("100");
        pnlDados.add(jLabel1);
        jLabel1.setBounds(180, 60, 30, 18);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");
        pnlDados.add(jLabel2);
        jLabel2.setBounds(10, 60, 20, 18);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("100");
        pnlDados.add(jLabel3);
        jLabel3.setBounds(180, 120, 30, 18);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");
        pnlDados.add(jLabel4);
        jLabel4.setBounds(10, 120, 20, 18);

        lblMunicao.setForeground(new java.awt.Color(255, 255, 255));
        lblMunicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlDados.add(lblMunicao);
        lblMunicao.setBounds(30, 80, 150, 20);

        lblVida.setForeground(new java.awt.Color(255, 255, 255));
        lblVida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlDados.add(lblVida);
        lblVida.setBounds(30, 140, 150, 20);

        getContentPane().add(pnlDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 270));

        pnlMonitor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceitar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnAceitar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceitar.setText("ACCEPT");
        btnAceitar.setBorderPainted(false);
        buttonGroup1.add(btnAceitar);
        btnAceitar.setContentAreaFilled(false);
        btnAceitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceitarActionPerformed(evt);
            }
        });
        pnlMonitor.add(btnAceitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        btnVoltar.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(153, 153, 153));
        btnVoltar.setText("BACK");
        btnVoltar.setBorderPainted(false);
        buttonGroup1.add(btnVoltar);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        pnlMonitor.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 80, 20));

        lblMissao.setFont(new java.awt.Font("Chilanka", 0, 18)); // NOI18N
        lblMissao.setForeground(new java.awt.Color(255, 255, 255));
        lblMissao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMissao.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        lblMissao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMonitor.add(lblMissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 330, 250));
        pnlMonitor.add(lblInimigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 130, 200));

        lblMonitor.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pnlMonitor.add(lblMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 610, 400));

        lblFundo1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pnlMonitor.add(lblFundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        getContentPane().add(pnlMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        btnSair.setFont(new java.awt.Font("Checkpoint Charlie", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(204, 204, 204));
        btnSair.setText("BACK");
        btnSair.setAutoscrolls(true);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 100, 50));

        btnDados.setBackground(new java.awt.Color(0, 0, 0));
        btnDados.setFont(new java.awt.Font("Checkpoint Charlie", 0, 15)); // NOI18N
        btnDados.setForeground(new java.awt.Color(255, 255, 255));
        btnDados.setText("LOJA");
        btnDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        btnCidade1.setBorderPainted(false);
        btnCidade1.setContentAreaFilled(false);
        btnCidade1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnCidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidade1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 20, 30));

        btnCidade2.setBorderPainted(false);
        btnCidade2.setContentAreaFilled(false);
        btnCidade2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnCidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidade2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCidade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 20, 30));

        btnCidade3.setBorderPainted(false);
        btnCidade3.setContentAreaFilled(false);
        btnCidade3.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnCidade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidade3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCidade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 20, 30));

        btnInterior4.setBorderPainted(false);
        btnInterior4.setContentAreaFilled(false);
        btnInterior4.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnInterior4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterior4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterior4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 20, 30));

        btnCidade5.setBorderPainted(false);
        btnCidade5.setContentAreaFilled(false);
        btnCidade5.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnCidade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidade5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCidade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 20, 30));

        btnInterior6.setBorderPainted(false);
        btnInterior6.setContentAreaFilled(false);
        btnInterior6.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnInterior6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterior6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterior6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 20, 30));

        btnInterior7.setBorderPainted(false);
        btnInterior7.setContentAreaFilled(false);
        btnInterior7.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnInterior7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterior7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterior7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 20, 30));

        btnCidade8.setBorderPainted(false);
        btnCidade8.setContentAreaFilled(false);
        btnCidade8.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnCidade8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidade8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCidade8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 20, 30));

        btnInterior9.setBorderPainted(false);
        btnInterior9.setContentAreaFilled(false);
        btnInterior9.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnInterior9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterior9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterior9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 20, 30));

        btnInterior10.setBorderPainted(false);
        btnInterior10.setContentAreaFilled(false);
        btnInterior10.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnInterior10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterior10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterior10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 20, 30));

        lblFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setInimigos(){
        objInimigo[0] = new Inimigo(0, "Trio", 10000, 10000, 200, 0, "/images/inimigos/00trio2.png");
        objInimigo[1] = new Inimigo(1, "Franklin", 100, 20, 10, 500, "/images/inimigos/01franklin.png");
        objInimigo[2] = new Inimigo(2, "Niko", 100, 55, 70, 1750, "/images/inimigos/02niko.png");
        objInimigo[3] = new Inimigo(3, "Michael", 100, 30, 15, 3000,"/images/inimigos/03michael.png");
        objInimigo[4] = new Inimigo(4, "dono do rottweiler", 100, 10, 100, 500, "/images/inimigos/04rottweiler.png");
        objInimigo[5] = new Inimigo(5, "a dupla da Mascara de Gás", 100, 55, 80, 1500, "/images/inimigos/05duplaMascarada.png");
        objInimigo[6] = new Inimigo(6, "o parceiro Michael", 100, 55, 40, 2000, "/images/inimigos/06parceiroMichael.png");
        objInimigo[7] = new Inimigo(7, "o trio", 100, 70, 65, 2200, "/images/inimigos/07trio1.png");
        objInimigo[8] = new Inimigo(8, "o policial corrupto", 100, 55, 10, 750, "/images/inimigos/08policial.png");
        objInimigo[9] = new Inimigo(9, "Michael novamente", 100, 55, 90, 15000, "/images/inimigos/09michael2.png");
        objInimigo[10] = new Inimigo(10, "Caramelo", 100, 100, 100, 00000, "/images/inimigos/10caramelo.png");
    }
    
    private void setTela(){
        Globais.ajustarImagem(getClass().getResource("/images/background/map.png"), lblFundo);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnCidade1);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnCidade2);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnCidade3);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnInterior4);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnCidade5);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnInterior6);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnInterior7);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnCidade8);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnInterior9);
        Globais.ajustarButton(getClass().getResource("/images/buttons/mapPoint.png"), btnInterior10);
        lblMonitor.setVisible(false);
        lblMissao.setVisible(false);
        btnAceitar.setVisible(false);
        btnVoltar.setVisible(false);
        pnlDados.setVisible(false);
        pnlMonitor.setVisible(false);
        pgbVida.setValue(personagemEscolhido.getVida());
        pgbMunicao.setValue(armaEscolhida.getMunicao());
        lblMoney.setText(String.valueOf(personagemEscolhido.getDinheiro()));
        lblVida.setText(String.valueOf(personagemEscolhido.getVida()));
        lblMunicao.setText(String.valueOf(armaEscolhida.getMunicao()));
        Globais.ajustarButton(getClass().getResource("/images/buttons/store.png"), btnStore);
        Globais.ajustarButton(getClass().getResource("/images/buttons/x.png"), btnSairDados);
        Globais.ajustarImagem(getClass().getResource("/images/history/money.png"), lblMoneyIco);
    }
    
    private void pontosMissoes(int idInimigo){
        btnCidade1.setVisible(false);
        btnCidade2.setVisible(false);
        btnCidade5.setVisible(false);
        btnCidade3.setVisible(false);
        btnCidade8.setVisible(false);
        btnInterior10.setVisible(false);
        btnInterior9.setVisible(false);
        btnInterior7.setVisible(false);
        btnInterior6.setVisible(false);
        btnInterior4.setVisible(false);
        switch(idInimigo){
            case 0:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnInterior4.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            btnCidade3.setEnabled(false);
            break;
            case 1:
            btnCidade1.setVisible(true);
            break;
            case 2:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade1.setEnabled(false);
            break;
            case 3:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            break;
            case 4:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnInterior4.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            btnCidade3.setEnabled(false);
            break;
            case 5:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnInterior4.setVisible(true);
            btnCidade5.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            btnCidade3.setEnabled(false);
            btnInterior4.setEnabled(false);
            break;
            case 6:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnInterior4.setVisible(true);
            btnCidade5.setVisible(true);
            btnInterior6.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            btnCidade3.setEnabled(false);
            btnInterior4.setEnabled(false);
            btnCidade5.setEnabled(false);
            break;
            case 7:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnInterior4.setVisible(true);
            btnCidade5.setVisible(true);
            btnInterior6.setVisible(true);
            btnInterior7.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            btnCidade3.setEnabled(false);
            btnInterior4.setEnabled(false);
            btnCidade5.setEnabled(false);
            btnInterior6.setEnabled(false);
            break;
            case 8:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnInterior4.setVisible(true);
            btnCidade5.setVisible(true);
            btnInterior6.setVisible(true);
            btnInterior7.setVisible(true);
            btnCidade8.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            btnCidade3.setEnabled(false);
            btnInterior4.setEnabled(false);
            btnCidade5.setEnabled(false);
            btnInterior6.setEnabled(false);
            btnInterior7.setEnabled(false);
            break;
            case 9:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnInterior4.setVisible(true);
            btnCidade5.setVisible(true);
            btnInterior6.setVisible(true);
            btnInterior7.setVisible(true);
            btnCidade8.setVisible(true);
            btnInterior9.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            btnCidade3.setEnabled(false);
            btnInterior4.setEnabled(false);
            btnCidade5.setEnabled(false);
            btnInterior6.setEnabled(false);
            btnInterior7.setEnabled(false);
            btnCidade8.setEnabled(false);
            break;
            case 10:
            btnCidade1.setVisible(true);
            btnCidade2.setVisible(true);
            btnCidade3.setVisible(true);
            btnInterior4.setVisible(true);
            btnCidade5.setVisible(true);
            btnInterior6.setVisible(true);
            btnInterior7.setVisible(true);
            btnCidade8.setVisible(true);
            btnInterior9.setVisible(true);
            btnInterior10.setVisible(true);
            btnCidade1.setEnabled(false);
            btnCidade2.setEnabled(false);
            btnCidade3.setEnabled(false);
            btnInterior4.setEnabled(false);
            btnCidade5.setEnabled(false);
            btnInterior6.setEnabled(false);
            btnInterior7.setEnabled(false);
            btnCidade8.setEnabled(false);
            btnInterior9.setEnabled(false);
            break;
        }
    }
    
    private void btnAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceitarActionPerformed
        TelaConfronto tela = new TelaConfronto(missao, personagemEscolhido, armaEscolhida, inimigo);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAceitarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Globais.ajustarImagem(getClass().getResource("/images/background/map.png"), lblFundo);
        pnlMonitor.setVisible(false);
        btnSair.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        TelaPersonagem tela = new TelaPersonagem();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidade1ActionPerformed
        inimigo = objInimigo[1];
        missao = 1;
        lblMissao.setText("<html>Recebemos um chamado do centro!<br/>Parece que um dos"
                + " capangas da gangue realizou um assalto e está dentro de um túnel"
                + " da cidade, te enviei uma foto dele.<br/><br/>Vá até la e enfrente-o.<html>");
        Globais.ajustarImagem(getClass().getResource("/images/inimigos/01franklin.png"), lblInimigo);
        mostrarMissao();
    }//GEN-LAST:event_btnCidade1ActionPerformed

    private void btnCidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidade2ActionPerformed
        inimigo = objInimigo[2];
        missao = 2;
        lblMissao.setText("<html>Um homem está atentando contra as pessoas na rua!<br/>"
        + "Ele está fortemente armado, vai ser dificil prendê-lo.<br/><br/>Resolva isso.<html>");
        mostrarMissao();
    }//GEN-LAST:event_btnCidade2ActionPerformed

    private void btnCidade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidade3ActionPerformed
        inimigo = objInimigo[3];
        mostrarMissao();
        missao = 3;
        lblMissao.setText("<html>Recebi relatos de que Michael, o chefe da gangue, está"
                + " no antigo armazém, vá até la e pegue-o de surpresa.<br/>"
                + "Estou desconfiando dos policiais daqui, trago mais informações em breve<br/>"
                + "<br/>Ele geralmente está vestindo terno, será fácil encontrá-lo.<html>");
    }//GEN-LAST:event_btnCidade3ActionPerformed

    private void btnInterior4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterior4ActionPerformed
        if (missao == 0) {
            inimigo = objInimigo[0];    
        } else {
            inimigo = objInimigo[4];
        }
        mostrarMissao();
        missao = 4;
        lblMissao.setText("<html>Um membro da gangue está ameaçando moradores do interior<br/>"
                + "<br/>Vá para la e veja o que consegue fazer.<html>");
    }//GEN-LAST:event_btnInterior4ActionPerformed

    private void btnCidade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidade5ActionPerformed
        inimigo = objInimigo[5];
        mostrarMissao();
        missao = 5;
        lblMissao.setText("<html>Uma dupla está na praça da cidade. <br/><br/>Pegue-os!<html>");
    }//GEN-LAST:event_btnCidade5ActionPerformed

    private void btnInterior6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterior6ActionPerformed
        inimigo = objInimigo[6];
        mostrarMissao();
        missao = 6;
        lblMissao.setText("<html>O braço direito de Michael foi avistado bebado "
                + "atirando para todos os lados na mata!<html>");
        
    }//GEN-LAST:event_btnInterior6ActionPerformed

    private void btnInterior7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterior7ActionPerformed
        inimigo = objInimigo[7];
        mostrarMissao();
        missao = 7;
        lblMissao.setText("<html>Recebemos um chamado do interior<br/>"
                + "Um trio da gangue está caçando animais na floresta<br/><br/>"
                + "Surpreenda-os e pegue-os!!<html>");
    }//GEN-LAST:event_btnInterior7ActionPerformed

    private void btnCidade8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidade8ActionPerformed
        inimigo = objInimigo[8];
        mostrarMissao();
        missao = 8;
        lblMissao.setText("<html>Lembra que te falei da policia daqui, então!<br/>"
                + "Descobri um oficial envolvido nos negócios da gangue.<br/><br/>"
                + "Ele está fazendo a segurança de um evento no parque de diversões<br/><br/>"
                + "Peguê-o urgentemente!<html>");
    }//GEN-LAST:event_btnCidade8ActionPerformed

    private void btnInterior9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterior9ActionPerformed
        inimigo = objInimigo[9];
        mostrarMissao();
        missao = 9;
        lblMissao.setText("<html>Michael conseguiu fugir da prisão, moradores do interior"
                + " falaram que ele está no interior, muito bem armado!<br/><br/>"
                + "Pegue-o novamente, você receberá outra recompenssa.<br/>Boa Sorte!<html>");
    }//GEN-LAST:event_btnInterior9ActionPerformed

    private void btnInterior10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterior10ActionPerformed
        inimigo = objInimigo[10];
        mostrarMissao();
        missao = 10;
        lblMissao.setText("<html>O cachorro de Michael está solto pelo interior, e "
                + "está amedrontando os motoqueiros.<br/> Acredito que deva ser sua última missão,"
                + " ja que a gangue foi embora da cidade.<html>");
    }//GEN-LAST:event_btnInterior10ActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        pnlDados.setVisible(true);
        btnDados.setVisible(false);
    }//GEN-LAST:event_btnDadosActionPerformed

    private void btnSairDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairDadosActionPerformed
        btnDados.setVisible(true);
        pnlDados.setVisible(false);
    }//GEN-LAST:event_btnSairDadosActionPerformed

    private void btnStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreActionPerformed
        TelaLoja tela = new TelaLoja(missao , personagemEscolhido, armaEscolhida);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStoreActionPerformed

    private void mostrarMissao(){
        pnlMonitor.setVisible(true);
        Globais.ajustarImagem(getClass().getResource("/images/history/monitor.png"), lblMonitor);
        Globais.ajustarImagem(getClass().getResource("/images/background/history.jpg"), lblFundo1);
        lblMonitor.setVisible(true);
        lblMissao.setVisible(true);
        btnAceitar.setVisible(true);
        btnVoltar.setVisible(true);
        btnSair.setVisible(false);
    }
    
//        /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaMissao().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar;
    private javax.swing.JButton btnCidade1;
    private javax.swing.JButton btnCidade2;
    private javax.swing.JButton btnCidade3;
    private javax.swing.JButton btnCidade5;
    private javax.swing.JButton btnCidade8;
    private javax.swing.JButton btnDados;
    private javax.swing.JButton btnInterior10;
    private javax.swing.JButton btnInterior4;
    private javax.swing.JButton btnInterior6;
    private javax.swing.JButton btnInterior7;
    private javax.swing.JButton btnInterior9;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSairDados;
    private javax.swing.JButton btnStore;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblFundo1;
    private javax.swing.JLabel lblInimigo;
    private javax.swing.JLabel lblMissao;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblMoneyIco;
    private javax.swing.JLabel lblMonitor;
    private javax.swing.JLabel lblMunicao;
    private javax.swing.JLabel lblRS;
    private javax.swing.JLabel lblVida;
    private javax.swing.JProgressBar pgbMunicao;
    private javax.swing.JProgressBar pgbVida;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlMonitor;
    // End of variables declaration//GEN-END:variables
}
