package screens;

import models.Personagem;
import tools.Globais;

/**
 *
 * @author maaschmidt
 */
public class TelaPersonagem extends javax.swing.JFrame {

    Personagem[] objPersonagem = new Personagem[3];

    /**
     * Creates new form TelaPersonagem
     */
    public TelaPersonagem() {
        initComponents();
        setPersonagem();
        setTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPersonagem = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        pgbVida = new javax.swing.JProgressBar();
        pgbInteligencia = new javax.swing.JProgressBar();
        pgbForca = new javax.swing.JProgressBar();
        pgbAgilidade = new javax.swing.JProgressBar();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPersonagem.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(lblPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 240, 380));

        lblNome.setFont(new java.awt.Font("Checkpoint Charlie", 0, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("null");
        lblNome.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 270, 60));

        btnNext.setFont(new java.awt.Font("Checkpoint Charlie", 0, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("NEXT");
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

        pgbVida.setFont(new java.awt.Font("Checkpoint Charlie", 0, 13)); // NOI18N
        pgbVida.setForeground(new java.awt.Color(51, 51, 51));
        pgbVida.setValue(75);
        pgbVida.setBorderPainted(false);
        pgbVida.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pgbVida.setString("VIDA");
        pgbVida.setStringPainted(true);
        getContentPane().add(pgbVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 140, 20));

        pgbInteligencia.setFont(new java.awt.Font("Checkpoint Charlie", 0, 13)); // NOI18N
        pgbInteligencia.setForeground(new java.awt.Color(51, 51, 51));
        pgbInteligencia.setValue(75);
        pgbInteligencia.setBorderPainted(false);
        pgbInteligencia.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pgbInteligencia.setString("INTELIGENCIA");
        pgbInteligencia.setStringPainted(true);
        getContentPane().add(pgbInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 140, 20));

        pgbForca.setFont(new java.awt.Font("Checkpoint Charlie", 0, 13)); // NOI18N
        pgbForca.setForeground(new java.awt.Color(51, 51, 51));
        pgbForca.setValue(75);
        pgbForca.setBorderPainted(false);
        pgbForca.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pgbForca.setString("FORCA");
        pgbForca.setStringPainted(true);
        getContentPane().add(pgbForca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 140, 20));

        pgbAgilidade.setFont(new java.awt.Font("Checkpoint Charlie", 0, 13)); // NOI18N
        pgbAgilidade.setForeground(new java.awt.Color(51, 51, 51));
        pgbAgilidade.setValue(75);
        pgbAgilidade.setBorderPainted(false);
        pgbAgilidade.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pgbAgilidade.setName("AGILIDADE"); // NOI18N
        pgbAgilidade.setString("AGILIDADE");
        pgbAgilidade.setStringPainted(true);
        getContentPane().add(pgbAgilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 140, 20));

        btnRight.setBorderPainted(false);
        btnRight.setContentAreaFilled(false);
        btnRight.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 220, 30, 30));

        btnLeft.setBorderPainted(false);
        btnLeft.setContentAreaFilled(false);
        btnLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, 30));

        lblFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        lblFundo.setOpaque(true);
        lblFundo.setPreferredSize(new java.awt.Dimension(730, 490));
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setPersonagem(){
        objPersonagem[0] = new Personagem(1, "SNIPER", 100, 40, 95, 20, 20, "/images/principais/sniper.png");
        objPersonagem[1] = new Personagem(2, "DESTEMIDO", 100, 70, 30, 95, 20, "/images/principais/destemido.png");
        objPersonagem[2] = new Personagem(3, "TATICO", 100, 85, 75, 60, 20, "/images/principais/tatico.png");
    }
    
    private void setTela(){
        Globais.ajustarImagem(getClass().getResource("/images/background/fumaca.png"), lblFundo);
        Globais.ajustarButton(getClass().getResource("/images/buttons/seta-left.png"), btnLeft);
        Globais.ajustarButton(getClass().getResource("/images/buttons/seta-right.png"), btnRight);
        mostrarPersonagem('<');
    }

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        mostrarPersonagem('>');
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        mostrarPersonagem('<');
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        TelaArma tela = null;
        if (lblNome.getText().equals(objPersonagem[0].getNome())) {
            tela = new TelaArma(objPersonagem[0]);
        } else if (lblNome.getText().equals(objPersonagem[1].getNome())) {
            tela = new TelaArma(objPersonagem[1]);
        } else if (lblNome.getText().equals(objPersonagem[2].getNome())) {
            tela = new TelaArma(objPersonagem[2]);
        }
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void mostrarPersonagem(char lado) {
        if (lblNome.getText().equals("null") && lado == '<') {
            destemido();
        } else if (lblNome.getText().equals(objPersonagem[0].getNome()) && lado == '>') {
            destemido();
        } else if (lblNome.getText().equals(objPersonagem[0].getNome()) && lado == '<') {
            tatico();
        } else if (lblNome.getText().equals(objPersonagem[1].getNome()) && lado == '>') {
            tatico();
        } else if (lblNome.getText().equals(objPersonagem[1].getNome()) && lado == '<') {
            sniper();
        } else if (lblNome.getText().equals(objPersonagem[2].getNome()) && lado == '<') {
            destemido();
        } else if (lblNome.getText().equals(objPersonagem[2].getNome()) && lado == '>') {
            sniper();
        }
    }

    private void sniper() {
        lblNome.setText(objPersonagem[0].getNome());
        pgbVida.setValue(objPersonagem[0].getVida());
        pgbAgilidade.setValue(objPersonagem[0].getAgilidade());
        pgbInteligencia.setValue(objPersonagem[0].getInteligencia());
        pgbForca.setValue(objPersonagem[0].getForca());
        Globais.ajustarImagem(getClass().getResource(objPersonagem[0].getCaminhoImagem()), lblPersonagem);
    }

    private void destemido() {
        lblNome.setText(objPersonagem[1].getNome());
        pgbVida.setValue(objPersonagem[1].getVida());
        pgbAgilidade.setValue(objPersonagem[1].getAgilidade());
        pgbInteligencia.setValue(objPersonagem[1].getInteligencia());
        pgbForca.setValue(objPersonagem[1].getForca());
        Globais.ajustarImagem(getClass().getResource(objPersonagem[1].getCaminhoImagem()), lblPersonagem);
    }

    private void tatico() {
        lblNome.setText(objPersonagem[2].getNome());
        pgbVida.setValue(objPersonagem[2].getVida());
        pgbAgilidade.setValue(objPersonagem[2].getAgilidade());
        pgbInteligencia.setValue(objPersonagem[2].getInteligencia());
        pgbForca.setValue(objPersonagem[2].getForca());
        Globais.ajustarImagem(getClass().getResource(objPersonagem[2].getCaminhoImagem()), lblPersonagem);
    }
    
//        /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPersonagem().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPersonagem;
    private javax.swing.JProgressBar pgbAgilidade;
    private javax.swing.JProgressBar pgbForca;
    private javax.swing.JProgressBar pgbInteligencia;
    private javax.swing.JProgressBar pgbVida;
    // End of variables declaration//GEN-END:variables
}
