package screens;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import tools.Globais;

/**
 *
 * @author maaschmidt
 */
public class TelaHistoria extends javax.swing.JFrame {

    String nomePlayer;

    /**
     * Creates new form TelaHistoria
     *
     * @param nomePlayer
     */
    public TelaHistoria(String nomePlayer) {
        this.nomePlayer = nomePlayer;
        iniciarTela();
    }

    TelaHistoria() {
        iniciarTela();
    }

    private void iniciarTela() {
        initComponents();
        try {
            Globais.ajustarImagem(getClass().getResource("/images/background/history.jpg"), lblFundo);
            Globais.ajustarImagem(getClass().getResource("/images/history/monitor.png"), lblMonitor);
        } catch (Exception ex) {
        }
        lblHistory.setText("<html>Olá "+nomePlayer+"!<br/><br/>Sou o responsável geral"
                + " da segurança no Vale do Taquari.<br/>Te mando essa mensagem urgente, "
                + "pois uma gangue está tentando tomar conta da cidade. Meus policiais "
                + "não estão conseguindo atender a todos chamados.<br/>Tenho recompensas "
                + "para cada integrante da gangue preso ou eliminado.<br/>"
                + "Você poderá também comprar café, que aumenta sua vida, e munição para "
                + "vencer.<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnSkip = new javax.swing.JButton();
        lblHistory = new javax.swing.JLabel();
        lblMonitor = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setFont(new java.awt.Font("Checkpoint Charlie", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(51, 51, 51));
        btnSair.setText("BACK");
        btnSair.setAutoscrolls(true);
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, 50));

        btnSkip.setFont(new java.awt.Font("Checkpoint Charlie", 0, 24)); // NOI18N
        btnSkip.setForeground(new java.awt.Color(102, 102, 102));
        btnSkip.setText("SKIP");
        btnSkip.setAutoscrolls(true);
        btnSkip.setBorderPainted(false);
        btnSkip.setContentAreaFilled(false);
        btnSkip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipActionPerformed(evt);
            }
        });
        getContentPane().add(btnSkip, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 100, 50));

        lblHistory.setFont(new java.awt.Font("Chilanka", 0, 18)); // NOI18N
        lblHistory.setForeground(new java.awt.Color(255, 255, 255));
        lblHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 500, 220));
        getContentPane().add(lblMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 610, 420));

        lblFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipActionPerformed
        TelaPersonagem tela = new TelaPersonagem();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSkipActionPerformed

    private void ajustarImagem(String caminho, JLabel label) {
        try {
            ImageIcon imageIcon = new ImageIcon(caminho);
            Image img = imageIcon.getImage();
            Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledimageIcon = new ImageIcon(imgScale);
            label.setIcon(scaledimageIcon);
        } catch (Exception ex) {
        }
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaHistoria().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSkip;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblMonitor;
    // End of variables declaration//GEN-END:variables
}
