package screens;

import models.Arma;
import models.Personagem;
import tools.Globais;

/**
 *
 * @author maaschmidt
 */
public class TelaArma extends javax.swing.JFrame {

    Arma[] objArma = new Arma[8];
    Personagem personagemAtivo = new Personagem();

    /**
     * Creates new form TelaPersonagem
     *
     * @param personagemAtivo
     */
    public TelaArma(Personagem personagemAtivo) {
        initComponents();
        this.personagemAtivo = personagemAtivo;
        setArma();
        setTela();
    }

    public TelaArma() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArma = new javax.swing.JLabel();
        lblNomeArma = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        pgbMunicao = new javax.swing.JProgressBar();
        pgbDano = new javax.swing.JProgressBar();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArma.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(lblArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 420, 130));

        lblNomeArma.setFont(new java.awt.Font("Checkpoint Charlie", 0, 24)); // NOI18N
        lblNomeArma.setForeground(new java.awt.Color(204, 204, 204));
        lblNomeArma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeArma.setText("null");
        lblNomeArma.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(lblNomeArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 260, 90));

        btnNext.setFont(new java.awt.Font("Checkpoint Charlie", 0, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("NEXT");
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

        btnSair.setFont(new java.awt.Font("Checkpoint Charlie", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(204, 204, 204));
        btnSair.setText("BACK");
        btnSair.setAutoscrolls(true);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 100, 50));

        pgbMunicao.setFont(new java.awt.Font("Checkpoint Charlie", 0, 13)); // NOI18N
        pgbMunicao.setForeground(new java.awt.Color(51, 51, 51));
        pgbMunicao.setValue(75);
        pgbMunicao.setBorderPainted(false);
        pgbMunicao.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pgbMunicao.setString("MUNICAO");
        pgbMunicao.setStringPainted(true);
        getContentPane().add(pgbMunicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 140, 20));

        pgbDano.setFont(new java.awt.Font("Checkpoint Charlie", 0, 13)); // NOI18N
        pgbDano.setForeground(new java.awt.Color(51, 51, 51));
        pgbDano.setValue(75);
        pgbDano.setBorderPainted(false);
        pgbDano.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        pgbDano.setString("DANO");
        pgbDano.setStringPainted(true);
        getContentPane().add(pgbDano, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 140, 20));

        btnRight.setBorder(null);
        btnRight.setBorderPainted(false);
        btnRight.setContentAreaFilled(false);
        btnRight.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 30, 30));

        btnLeft.setBorderPainted(false);
        btnLeft.setContentAreaFilled(false);
        btnLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, 30));

        lblFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        lblFundo.setOpaque(true);
        lblFundo.setPreferredSize(new java.awt.Dimension(730, 490));
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setArma(){
        objArma[0] = new Arma(1, "DRAGUNOV SVD-63", 50, 55, "/images/arma/sniper/dragunov-svd-63.png");
        objArma[1] = new Arma(1, "BARRETT M82", 30, 70, "/images/arma/sniper/barrett-m82.png");
        objArma[2] = new Arma(2, "M-249", 90, 10, "/images/arma/destemido/m249.png");
        objArma[3] = new Arma(2, "RPD", 80, 20, "/images/arma/destemido/rpd.png");
        objArma[4] = new Arma(2, "AK-47", 70, 15, "/images/arma/destemido/ak47.png");
        objArma[5] = new Arma(3, "HK416", 60, 45, "/images/arma/tatico/hk416.png");
        objArma[6] = new Arma(3, "M16", 55, 50, "/images/arma/tatico/m16.png");
        objArma[7] = new Arma(3, "MK10", 65, 40, "/images/arma/tatico/mk10.png");
    }
    
    private void setTela(){
        Globais.ajustarImagem(getClass().getResource("/images/background/fumaca.png"), lblFundo);
        Globais.ajustarButton(getClass().getResource("/images/buttons/seta-left.png"), btnLeft);
        Globais.ajustarButton(getClass().getResource("/images/buttons/seta-right.png"), btnRight);
        mostrarArma('<');
    }
    
    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        mostrarArma('>');
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        mostrarArma('<');
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        TelaPersonagem tela = new TelaPersonagem();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        Arma arma = new Arma();
        switch (personagemAtivo.getId()) {
            case 1:
                if (lblNomeArma.getText().equals(objArma[0].getNome())) {
                    arma = objArma[0];
                } else if (lblNomeArma.getText().equals(objArma[1].getNome())) {
                    arma = objArma[1];
                }   break;
            case 2:
                if (lblNomeArma.getText().equals(objArma[2].getNome())) {
                    arma = objArma[2];
                } else if (lblNomeArma.getText().equals(objArma[3].getNome())) {
                    arma = objArma[3];
                } else if (lblNomeArma.getText().equals(objArma[4].getNome())) {
                    arma = objArma[4];
                }   break;
            case 3:
                if (lblNomeArma.getText().equals(objArma[5].getNome())) {
                    arma = objArma[5];
                } else if (lblNomeArma.getText().equals(objArma[6].getNome())) {
                    arma = objArma[6];
                } else if (lblNomeArma.getText().equals(objArma[7].getNome())) {
                    arma = objArma[7];
                }   break;
            default:
                break;
        }
        TelaMissao tela = new TelaMissao(personagemAtivo, arma);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void mostrarArma(char lado) {
        switch (personagemAtivo.getId()) {
            case 1:
                if (lblNomeArma.getText().equals("null") && lado == '<') {
                    dragunov();
                } else if (lblNomeArma.getText().equals(objArma[0].getNome()) && lado == '>') {
                    barrett();
                } else if (lblNomeArma.getText().equals(objArma[0].getNome()) && lado == '<') {
                    barrett();
                } else if (lblNomeArma.getText().equals(objArma[1].getNome()) && lado == '>') {
                    dragunov();
                } else if (lblNomeArma.getText().equals(objArma[1].getNome()) && lado == '<') {
                    dragunov();
                }   break;
            case 2:
                if (lblNomeArma.getText().equals("null") && lado == '<') {
                    rpd();
                } else if (lblNomeArma.getText().equals(objArma[2].getNome()) && lado == '>') {
                    rpd();
                } else if (lblNomeArma.getText().equals(objArma[2].getNome()) && lado == '<') {
                    ak47();
                } else if (lblNomeArma.getText().equals(objArma[3].getNome()) && lado == '>') {
                    ak47();
                } else if (lblNomeArma.getText().equals(objArma[3].getNome()) && lado == '<') {
                    m249();
                } else if (lblNomeArma.getText().equals(objArma[4].getNome()) && lado == '>') {
                    m249();
                } else if (lblNomeArma.getText().equals(objArma[4].getNome()) && lado == '<') {
                    rpd();
                }   break;
            case 3:
                if (lblNomeArma.getText().equals("null") && lado == '<') {
                    m16();
                } else if (lblNomeArma.getText().equals(objArma[5].getNome()) && lado == '>') {
                    m16();
                } else if (lblNomeArma.getText().equals(objArma[5].getNome()) && lado == '<') {
                    mk10();
                } else if (lblNomeArma.getText().equals(objArma[6].getNome()) && lado == '<') {
                    hk416();
                } else if (lblNomeArma.getText().equals(objArma[6].getNome()) && lado == '>') {
                    mk10();
                } else if (lblNomeArma.getText().equals(objArma[7].getNome()) && lado == '<') {
                    m16();
                } else if (lblNomeArma.getText().equals(objArma[7].getNome()) && lado == '>') {
                    hk416();
                }   break;
            default:
                break;
        }
    }

    private void dragunov() {
        lblNomeArma.setText(objArma[0].getNome());
        pgbMunicao.setValue(objArma[0].getMunicao());
        pgbDano.setValue(objArma[0].getDano());
        Globais.ajustarImagem(getClass().getResource(objArma[0].getCaminhoImagem()), lblArma);
    }
    
        private void barrett() {
        lblNomeArma.setText(objArma[1].getNome());
        pgbMunicao.setValue(objArma[1].getMunicao());
        pgbDano.setValue(objArma[1].getDano());
        Globais.ajustarImagem(getClass().getResource(objArma[1].getCaminhoImagem()), lblArma);
    }
        
    private void m249() {
        lblNomeArma.setText(objArma[2].getNome());
        pgbMunicao.setValue(objArma[2].getMunicao());
        pgbDano.setValue(objArma[2].getDano());
        Globais.ajustarImagem(getClass().getResource(objArma[2].getCaminhoImagem()), lblArma);
    }
    
    private void rpd() {
        lblNomeArma.setText(objArma[3].getNome());
        pgbMunicao.setValue(objArma[3].getMunicao());
        pgbDano.setValue(objArma[3].getDano());
        Globais.ajustarImagem(getClass().getResource(objArma[3].getCaminhoImagem()), lblArma);
    }
            
    private void ak47() {
        lblNomeArma.setText(objArma[4].getNome());
        pgbMunicao.setValue(objArma[4].getMunicao());
        pgbDano.setValue(objArma[4].getDano());
        Globais.ajustarImagem(getClass().getResource(objArma[4].getCaminhoImagem()), lblArma);
    }
    
    private void hk416() {
        lblNomeArma.setText(objArma[5].getNome());
        pgbMunicao.setValue(objArma[5].getMunicao());
        pgbDano.setValue(objArma[5].getDano());
        Globais.ajustarImagem(getClass().getResource(objArma[5].getCaminhoImagem()), lblArma);
    }
    
    private void m16() {
        lblNomeArma.setText(objArma[6].getNome());
        pgbMunicao.setValue(objArma[6].getMunicao());
        pgbDano.setValue(objArma[6].getDano());
        Globais.ajustarImagem(getClass().getResource(objArma[6].getCaminhoImagem()), lblArma);
    }
            
    private void mk10() {
        lblNomeArma.setText(objArma[7].getNome());
        pgbMunicao.setValue(objArma[7].getMunicao());
        pgbDano.setValue(objArma[7].getDano());
        Globais.ajustarImagem(getClass().getResource(objArma[7].getCaminhoImagem()), lblArma);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblArma;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNomeArma;
    private javax.swing.JProgressBar pgbDano;
    private javax.swing.JProgressBar pgbMunicao;
    // End of variables declaration//GEN-END:variables

}
